src/Entity/ProduceItem.php
<?php
namespace App\Entity;

use App\Entity\Icon;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduceRepository")
 */
class ProduceItem {

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $name;
    /**
     * @ORM\Column(type="datetime")
     */
    private $expiration_date;

    /**
     * @ORM\OneToOne(targetEntity="Icon")
     */
    public $icon;

// Add new property - bool to indicate if item is in shopping list or not
    /**
     * @ORM\Column(type="boolean")
     */
    public $isInShoppingList;

    public function __construct() {
        $this->expiration_date
            =
            new
            \DateTime();
    }

    public function getId() {
        return $this->id;
    }

    public function getName() {
        return $this->name;
    }

    public function setName($name) {
        $this->name = $name;
    }

    public function getExpirationDate() : \DateTime {
        return $this->expiration_date;
    }

    public function setExpirationDate($expiration_date) {
        $this->expiration_date = $expiration_date;
    }

    public function getIcon() {
        return $this->icon;
    }

    public function setIcon($icon) {
        $this->icon = $icon;
    }

    public function getIsInShoppingList() {
        return $this->isInShoppingList;
    }

    public function setIsInShoppingList($isInShoppingList) {
        $this->isInShoppingList = $isInShoppingList;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body>
    <div class="container">
        {% block body %}
            <div>
            I am an html element form base.html.twig
            </div>
        {% endblock %}
        {% block javascripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script
                    src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
                    integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
                    crossorigin="anonymous">
            </script>
        {% endblock %}
    </div>
    </body>
</html>

templates/lucky_number.html.twig
{% extends 'base.html.twig' %}

    {% block title %}Hello symfony{% endblock %}

{% block stylesheets %}
    <style>
    .even {
        width: 100px;
        height: 100px;
        background-color: red;
    }

    .odd {
        width: 100px;
        height: 100px;
        background-color: blue;
    }
    </style>
{% endblock %}

{% block body %}
        <h1>HIIIIIIIIII</h1>
    {{ parent() }}
        <div>
            {{ random_number }}

            {% for letter in 'a'|upper..'z'|upper %}
            * {{ letter }}
            {% endfor %}

            {% for n in 1..9 %}
                * {{ n }}
            {% endfor %}

            <ul>
            {% for user in users %}
                <li>{{ user.username|upper}}</li>
            {% endfor %}
            </ul>

            {% if random_number > 50 %}
                <div>
                    What a bank number~!
                </div>
            {% elseif random_number < 50 and random_number > 25 %}
            <div>
                Not too big / nut 2 small.
            </div>
            {% else %}
                <div>
                    What a small numbor. A filthy mess
                </div>
            {% endif  %}

            {%  for i in 1..random_number %}
                <div class="{{ cycle(['even', 'odd'], i) }}">
                    {{ i }}
                    <!-- some html would go here -->
                </div>
            {% endfor %}
        </div>
{% endblock %}

templates/new-icon.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Icon{% endblock %}

{% block body %}

    <div>
        {{ form_start(icon_form) }}

            <div class="form-group">
                {{ form_label(icon_form.iconName) }}
                {{ form_widget(icon_form.iconName, {'attr': {'class' : 'form-control'} }) }}
            </div>

            <div class="form-group">
                {{ form_label(icon_form.iconImage) }}
                {{ form_widget(icon_form.iconImage, {'attr': {'class' : 'form-control'} }) }}
            </div>

            <div>
                {{ form_widget(icon_form.save, {'attr': {'class' : 'btn btn-primary'} }) }}
                <a class="btn btn-danger" href="new-produce-item">Cancel Upload</a>
            </div>

        {{ form_end(icon_form) }}
    </div>
{% endblock %}

templates/new-produce-item.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ label }}{% endblock %}

{% block body %}

    <div class="mt-5">
        {{ form_start(produce_item_form) }}
        <img class="mt-4 mb-4" src="/uploads/refrig.jpg" style="height: 200px"; width="200px">

        <div>
            {{ form_label(produce_item_form.icon) }}
            {{ form_widget(produce_item_form.icon, {'attr': {'class' : 'dropdown-toggle'} }) }}

            <a href="{{ path('icon') }}">
                {{ form_widget(produce_item_form.uploadIcon, {'attr': {'class' : 'btn btn-warning'} }) }}
            </a>
        </div>

        <div class="form-group">
            {{ form_label(produce_item_form.name) }}
            {{ form_widget(produce_item_form.name, {'attr': {'class' : 'form-control'} }) }}
        </div>

        <div class="form-group">
            {{ form_label(produce_item_form.expirationDate) }}
            {{ form_widget(produce_item_form.expirationDate, {'attr': {'class' : 'form-control'} }) }}
        </div>

        <div>
            {{ form_widget(produce_item_form.save, {'attr': {'class' : 'btn btn-primary'}, 'label': label }) }}
            <a class="btn btn-success" href="{{ path('refrigerator') }}">View My Refrigerator</a>
        </div>

        {{ form_end(produce_item_form) }}
    </div>


{% endblock %}

{% block javascripts %}
{{ parent() }}
    <script>
        $(document).ready(function() {
            $('#ajax-update').click(function(e) {
                let name = $('#produceItem_name').val();
                let expirationDate = $('#produceItem_expirationDate').val();
                let icon = $('#produceItem_icon').val();

                $.ajax({
                    url: $(this).data('url'),
                    method: 'PUT',
                    data: { name: name, expirationDate: expirationDate, icon: icon }
            }).done(function() {
                    $('#alert-div').html('<div class="alert alert-success p-5">Success!</div>');
                })
            });
        });
    </script>
{% endblock %}

templates/new-shopping-list-item.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Shopping List Item{% endblock %}

{% block body %}

    <div>
        {{ form_start(shopping_item_form) }}
        <img class="mt-4 mb-4" src="/uploads/basket.jpg" style="height: 200px"; width="200px">

        <div>
            {{ form_label(shopping_item_form.icon) }}
            {{ form_widget(shopping_item_form.icon, {'attr': {'class' : 'dropdown-toggle'} }) }}

            <a href="{{ path('icon') }}">
                {{ form_widget(shopping_item_form.uploadIcon, {'attr': {'class' : 'btn btn-warning'} }) }}
            </a>
        </div>

        <div class="form-group">
            {{ form_label(shopping_item_form.name) }}
            {{ form_widget(shopping_item_form.name, {'attr': {'class' : 'form-control'} }) }}
        </div>

        <div>
            {{ form_widget(shopping_item_form.save, {'attr': {'class' : 'btn btn-primary'} }) }}
            <a class="btn btn-success" href="items/shopping-list">View My Shopping List</a>
        </div>

        {{ form_end(shopping_item_form) }}
    </div>
{% endblock %}

templates/new-task.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div>
        {{ form_start(task_form) }}

        <div class="form-group">
            {{ form_label(task_form.description) }}
            {{ form_widget(task_form.description, {'attr': {'class' : 'form-control'} }) }}
        </div>

        <div class="form-group">
            {{ form_label(task_form.dueDate) }}
            {{ form_widget(task_form.dueDate, {'attr': {'class' : 'form-control'} }) }}
        </div>

        <div>
            {{ form_label(task_form.image) }}
            {{ form_widget(task_form.image) }}
        </div>

        <div>
            {{ form_widget(task_form.save, {'attr': {'class' : 'btn btn-primary'} }) }}
        </div>

        {{ form_end(task_form) }}
    </div>
{% endblock %}

templates/produce_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Refrigerator{% endblock %}

{% block body %}
    <a class="btn btn-success" href="shopping-list">View My Shopping List</a>
    <a class="btn btn-primary" href="../new-produce-item">Create New Produce Item</a>
    <a class="btn btn-primary" href="../new-shopping-list-item">Create New Shopping List Item</a>

    <h1>My Refrigerator</h1>
    <img class="mt-4 mb-4" src="/uploads/refrig.jpg" style="height: 200px"; width="200px">

    <div class="list-group">

        {% if rItem is defined %}
            {{ rItem.Id }}.
            {{ rItem.name }} -
            {{ rItem.expirationDate is empty ? "No Date set!" : rItem.expirationDate|date('d/m/Y') }}
        {% endif %}

        {% if items is defined %}
            <ul class="list-unstyled list-group">
                {% for item in items %}

                        <div class="d-flex w-400 justify-content-between list-group-item">
                            <h4 class="list-group-item-heading">
                                <li id="{{ item.Id }}-list-item" style="padding: 0px 30px;" class=
                                    "{% if item.expirationDate < date('+3 days')  %}alert-danger
                                    {% elseif item.expirationDate < date('+5 days') %}alert-warning
                                    {% endif %}">

                                    <div class="col-md-2 ">
                                        <img style="height: 30px; width: 30px" src="/uploads/{{ item.icon.getIconImage() }}"/>
                                    </div>

                                    <div class="col-md-2">
                                        {{ item.name }}
                                    </div>

                                    <div class="col-md-2">
                                        {{ item.expirationDate is empty ? "No Date set!" : item.expirationDate|date('d/m/Y') }}
                                    </div>

                                    <div class="col-md-2">
                                        <a href="{{ path('edit_refItem', { id: item.Id }) }}">
                                            <i class="fas fa-pencil-alt text-primary"></i>
                                        </a>

                                        <span data-url={{ path('delete_refItem', { id: item.Id }) }} id="{{ item.Id }}">
                                            <i class="fas fa-trash-alt text-danger"></i>
                                        </span>
                                    </div>

                                    <button data-url={{ path("ref_to_list", { id: item.Id }) }} id="{{ item.Id }}" class="btn btn-success">
                                        Add To Shopping List
                                    </button>
                                </li>
                            </h4>
                        </div>

                {% endfor %}
            </ul>
        {% endif %}

    {% if iconNames is defined %}
        <h1>All Icon Names</h1>

        {% for icon in iconNames %}

            <a href="#" class="list-group-item">
                <div class="d-flex w-100 justify-content-between">
                    <img src="/uploads/{{ icon.iconImage }}"/>
                    <h4 class="list-group-item-heading">
                        {{ icon.iconName }} <img src="/uploads/{{ icon.iconImage }}"/>
                    </h4>
                </div>
            </a>

        {% endfor %}
    {% endif %}

    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            $('ul li span').click(function(e) {
                let item_id = $(this).attr('Id');

                $.ajax({
                    url: $(this).data('url'),
                    method: 'DELETE'
                }).done(function() {
                    $('#' + item_id + '-list-item').hide();
                });
            });

            $('ul li button').click(function(e) {
                let item_id = $(this).attr('Id');

                $.ajax({
                    url: $(this).data('url'),
                    method: 'PUT'
                }).done(function() {
                    $('#' + item_id + '-list-item').hide();
                });
            })
        });
    </script>
{% endblock %}

templates/shopping_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}My Shopping List{% endblock %}

{% block body %}
    <a class="btn btn-success" href="refrigerator">View My Refrigerator</a>
    <a class="btn btn-primary" href="../new-produce-item">Create New Produce Item</a>
    <a class="btn btn-primary" href="../new-shopping-list-item">Create New Shopping List Item</a>

    <h1>My Shopping List</h1>
    <img class="mt-4 mb-4" src="/uploads/basket.jpg" style="height: 200px"; width="200px">

    <div class="list-group">

        {% for item in items %}

        <ul class="list-unstyled list-group">

                <div class="d-flex w-400 justify-content-between list-group-item">
                    <h4 class="list-group-item-heading">
                        <li id="{{ item.Id }}-list-item" style="padding: 0px 30px;">

                            <div class="col-md-2 ">
                                <img style="height: 30px; width: 30px" src="/uploads/{{ item.icon.getIconImage() }}"/>
                            </div>

                            <div class="col-md-3 ">
                                {{ item.name }}
                            </div>

                            <div class="col-md-2 ">
                                <span data-url={{ path('delete_refItem', { id: item.Id }) }} id="{{ item.Id }}">
                                    <i class="fas fa-trash-alt text-danger"></i>
                                </span>
                            </div>

                            <button data-url={{ path("list-to-ref", { id: item.Id }) }} id="{{ item.Id }}" class="btn btn-success">
                                Bought
                            </button>
                        </li>
                    </h4>
                </div>

        {% endfor %}
        </ul>

        {% if iconNames is defined %}
            <h1>All Icon Names</h1>

            {% for icon in iconNames %}

                <a href="#" class="list-group-item">
                    <div class="d-flex w-100 justify-content-between">
                        <h4 class="list-group-item-heading">
                            <img src="../uploads/{{ icon.iconImage }}"/>
                        </h4>
                    </div>
                </a>

            {% endfor %}
        {% endif %}

    <a href="{{ path("shopping_list_download") }}" class="btn btn-info">
        <i class="fas fa-download"></i> Download
    </a>

    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        $(document).ready(function() {
            // delete
            $('ul li span').click(function(e) {
                let item_id = $(this).attr('Id');

                $.ajax({
                    url: $(this).data('url'),
                    method: 'DELETE'
                }).done(function() {
                    $('#' + item_id + '-list-item').hide();
                });
            })

            // Move to refrigerator button
            $('ul li button').click(function(e) {
                let item_id = $(this).attr('Id');

                $.ajax({
                    url: $(this).data('url'),
                    method: 'PUT'
                }).done(function() {
                    $('#' + item_id + '-list-item').hide();
                });
            })
        });
    </script>
{% endblock %}

templates/start.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome{% endblock %}

{% block body %}
    <div class="text-center">

        <h1 class="text-center">Welcome!</h1>

        <div style="padding: 25px">
            <img class="mt-4 mb-4" src="/uploads/refrig.jpg" style="height: 200px"; width="200px">
        </div>

        <div class="text-center">
            <a class="btn btn-success" href="{{ path('shopping_list') }}" >View My Shopping List</a>
            <a class="btn btn-success" href="{{ path('refrigerator') }}">View My Refrigerator</a>
        </div>

        <div style="padding: 25px">
            <a class="btn btn-primary" href="{{ path('new_shopping_list_item') }}">Create New Shopping List Item</a>
            <a class="btn btn-primary" href="{{ path('new_produce_item') }}">Create New Produce Item</a>
        </div>

    </div>

{% endblock %}